version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: product_service
    ports:
      - "3308:3308"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
